  <svg class="icon-defs" aria-hidden="true"><defs>
    <symbol id="studio-i-arrow" viewBox="0 0 24 24"><path d="M4 12h16m-6-6 6 6-6 6"/></symbol>
    <symbol id="studio-i-save" viewBox="0 0 24 24"><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></symbol>
    <symbol id="studio-i-reset" viewBox="0 0 24 24"><path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/></symbol>
    <symbol id="studio-i-zoom" viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5M7.5 10.5h6m-3-3v6"/></symbol>
    <symbol id="studio-i-close" viewBox="0 0 24 24"><path d="m6 6 12 12M6 18 18 6"/></symbol>
    <symbol id="studio-i-check" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></symbol>
    <symbol id="studio-i-cart" viewBox="0 0 24 24"><path d="M3 4h2l2 11h11l3-9H6"/><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></symbol>
    <symbol id="studio-i-room" viewBox="0 0 24 24"><path d="m3 6 9-3 9 3v15H3ZM12 3v18m-9-9 9 3 9-3"/></symbol>
  </defs></svg>
    <div class="intro"><div><h1>{{ trans("configurator.heading") }}</h1><p class="studio-lead">{{ trans("configurator.lead") }}</p></div><div class="intro-download" id="studio-intro-download"><p>{{ $ui['Завантажте створений ескіз'] }}</p><button class="icon-button studio-reset" id="studio-reset" aria-label="{{ $ui['Скинути налаштування'] }}" title="{{ $ui['Скинути налаштування'] }}"><svg><use href="#studio-i-reset"/></svg></button><button class="button button-dark" id="studio-save" aria-label="{{ $ui['Зберегти образ'] }}" disabled><svg><use href="#studio-i-save"/></svg><span>{{ $ui['Зберегти образ'] }}</span></button></div></div>
    <div class="workspace">
      <section class="visual-column" aria-label="{{ $ui['Візуалізація інтер’єру'] }}">
        <div class="room-toolbar"><div class="room-control"><span class="step-label">{{ $ui['Ваш простір'] }}</span><div class="room-options" id="studio-rooms" role="group" aria-label="{{ $ui['Тип кімнати'] }}"></div></div><div id="studio-wall-toolbar"><div class="wall-control"><div class="wall-title"><span class="step-label">{{ $ui['Колір стін'] }}</span><span id="studio-wall-name" hidden>{{ $ui['Теплий кашемір'] }}</span></div><div class="palette-row"><div class="palette" id="studio-wall-palette" role="group" aria-label="{{ $ui['Колір стін'] }}"></div><div class="custom-color"><label for="studio-custom-color" title="{{ $ui['Свій відтінок'] }}"><span aria-hidden="true">+</span><input id="studio-custom-color" type="color" value="#c2b8a8" aria-label="{{ $ui['Свій відтінок'] }}" aria-describedby="studio-wall-hex"></label><span id="studio-wall-hex" class="sr-only">#C2B8A8</span></div></div></div></div></div>
        <div class="scene" id="studio-scene">
          <canvas id="studio-room-canvas" width="1536" height="1024" role="img" aria-label="{{ $ui['Візуалізація обраних дверей в інтер’єрі'] }}"></canvas>
          <div id="studio-scene-loading" class="scene-loading" role="status">{{ $ui['Готуємо ваш простір…'] }}</div>
          <span id="studio-scene-status" class="scene-status" role="status" hidden>{{ $ui['Оновлюємо ескіз…'] }}</span>
          <div class="scene-topline"><button class="scene-zoom icon-button" id="studio-zoom" aria-label="{{ $ui['Розглянути двері зблизька'] }}" title="{{ $ui['Розглянути двері зблизька'] }}"><svg><use href="#studio-i-zoom"/></svg></button></div>
          <div class="scene-navigation" aria-label="{{ $ui['Швидка зміна дверей'] }}"><button id="studio-previous-door" aria-label="{{ $ui['Попередня модель дверей'] }}"><svg><use href="#studio-i-arrow"/></svg></button><span><strong id="studio-door-counter">1 / 4</strong><small>{{ $ui['Гортайте двері'] }}</small></span><button id="studio-next-door" aria-label="{{ $ui['Наступна модель дверей'] }}"><svg><use href="#studio-i-arrow"/></svg></button></div>
        </div>
        <div class="studio-error" id="studio-scene-error" role="alert" hidden><p>{{ $ui['Зображення не завантажилося. Перевірте з’єднання або оберіть іншу модель.'] }}</p><button id="studio-retry-scene">{{ $ui['Спробувати ще раз'] }}</button></div>
        <p class="scene-note" id="studio-scene-note">{{ $ui['Візуальна примірка, не точний 3D-проєкт. Відтінки, масштаб і вигляд ручки — орієнтовні.'] }}</p>
      </section>
      <aside class="selection-panel" aria-label="{{ $ui['Налаштування дверей'] }}">
        <div class="panel-tabs" role="tablist" aria-label="{{ $ui['Каталог для примірки'] }}"><button id="studio-tab-doors" role="tab" aria-selected="true" aria-controls="studio-door-panel">{{ $ui['Двері'] }}</button><button id="studio-tab-handles" role="tab" aria-selected="false" aria-controls="studio-handle-panel" tabindex="-1">{{ $ui['Ручки'] }}</button></div>
        <div id="studio-door-panel" role="tabpanel" aria-labelledby="studio-tab-doors">
          <div class="door-type-control"><span class="door-type-caption" id="studio-door-type-label">{{ $ui['Тип дверей'] }}</span><div id="studio-door-types" role="group" aria-labelledby="studio-door-type-label" aria-describedby="studio-door-help"></div><label class="door-type-select-label" for="studio-door-type-select">{{ $ui['Тип дверей'] }}</label><select id="studio-door-type-select" aria-describedby="studio-door-help"></select></div>
          <p class="sr-only" id="studio-door-help">{{ $ui['Моделі для примірки з каталогу Bona Doors'] }}</p><div class="product-grid" id="studio-door-grid"></div><div class="finish-section"><div class="finish-heading"><span>{{ $ui['Відтінок дверей'] }}</span><strong id="studio-door-color-name"></strong></div><div id="studio-door-finishes" class="door-finishes" role="group" aria-label="{{ $ui['Відтінок дверей'] }}"></div></div>
        </div>
        <div id="studio-handle-panel" role="tabpanel" aria-labelledby="studio-tab-handles" hidden><p class="panel-help" id="studio-handle-help">{{ $ui['Оберіть ручку — її вартість додасться окремим рядком'] }}</p><div id="studio-handle-grid" class="handle-grid"></div><button id="studio-no-handle" class="no-handle" aria-pressed="true">{{ $ui['Без додаткової ручки'] }}</button><p id="studio-handle-notice" class="handle-notice"></p><button id="studio-interior-handles" class="button button-outline" hidden>{{ $ui['Обрати міжкімнатні двері'] }}<svg><use href="#studio-i-arrow"/></svg></button></div>
        <div class="selection-summary"><p class="eyebrow">{{ $ui['ВАШ ВИБІР'] }}</p><div class="selection-line"><div><span class="selection-label">{{ $ui['Двері'] }}</span><h2><a id="studio-selected-product-link"><span id="studio-selected-name"></span></a></h2><small id="studio-selected-availability"></small><small id="studio-selected-details"></small></div><strong id="studio-selected-price"></strong></div><div id="studio-selected-handle-row" class="selection-line handle-selection" hidden><div><span class="selection-label">{{ $ui['Ручка'] }}</span><span id="studio-selected-handle-name"></span></div><strong id="studio-selected-handle-price"></strong></div><div class="selection-order"><div><span>{{ $ui['Разом'] }}</span><strong id="studio-selection-total"></strong></div><button id="studio-order-selection" class="button button-dark" aria-haspopup="dialog" aria-controls="bona-cart-drawer"><span id="studio-order-label">{{ $ui['Замовити'] }}</span><svg><use href="#studio-i-arrow"/></svg></button></div><p class="price-note">{{ $ui['Ціна стосується обраних позицій. Коробка, лиштва, монтаж і доставка не додаються автоматично. Перед оплатою уточніть комплектацію та сумісність ручки.'] }}</p></div>
        <div id="studio-cart-error" class="studio-error" role="alert" hidden><p id="studio-cart-error-message"></p><button id="studio-reload">{{ $ui['Оновити сторінку'] }}</button></div><div id="studio-mobile-selection-footer"></div>
      </aside>
    </div>
  <dialog id="studio-detail-dialog" aria-labelledby="studio-detail-title"><div class="dialog-heading"><div><p class="eyebrow">{{ $ui['БЛИЖЧЕ ДО ДЕТАЛЕЙ'] }}</p><h2 id="studio-detail-title">{{ $ui['Ваші двері'] }}</h2></div><button id="studio-close-detail" class="icon-button" aria-label="{{ $ui['Закрити перегляд'] }}"><svg><use href="#studio-i-close"/></svg></button></div><canvas id="studio-detail-canvas" width="800" height="1000" role="img" aria-label="{{ $ui['Збільшена примірка дверей і ручки'] }}"></canvas><p id="studio-detail-caption"></p></dialog>
<div class="toast" id="studio-toast" role="status" aria-live="polite"></div><noscript>{{ $ui['Для примірки дверей увімкніть JavaScript у браузері.'] }}</noscript>
