name: Deployment to the server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Copy files to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          # Replace 'public/build' with the actual path to your local directory
          local_path="public/build"

          # Replace '~/lonch.digital/bona/public/build-dep/' with the actual path on the remote server
          remote_path="~/lonch.digital/bona/public/build-dep/"

          # Create the remote directory if it doesn't exist
          mkdir -p "$remote_path"

          # Copy files from local machine to remote server
          rsync -r "$local_path"/* "$remote_path"
